FROM golang

WORKDIR /orderService

COPY . .

RUN apt-get update

RUN go get -u github.com/micro/plugins/v5/registry/consul

RUN go get -u google.golang.org/protobuf/proto

RUN go get -u go-micro.dev/v5

RUN go build -o orderService .

EXPOSE 8080

CMD [ "./orderService" ]